// Mocks generated by Mockito 5.4.6 from annotations
// in flockinator/test/src/features/flock_scan/application/flock_scan_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:dchs_flutter_beacon/dchs_flutter_beacon.dart' as _i4;
import 'package:flockinator/src/features/flock_scan/domain/flock_scan_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$FlockScanModelCopyWith_1<$Res> extends _i1.SmartFake
    implements _i2.$FlockScanModelCopyWith<$Res> {
  _Fake$FlockScanModelCopyWith_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FlockScanModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlockScanModel extends _i1.Mock implements _i2.FlockScanModel {
  MockFlockScanModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get proximityUUID =>
      (super.noSuchMethod(
            Invocation.getter(#proximityUUID),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#proximityUUID),
            ),
          )
          as String);

  @override
  int get rssi =>
      (super.noSuchMethod(Invocation.getter(#rssi), returnValue: 0) as int);

  @override
  double get accuracy =>
      (super.noSuchMethod(Invocation.getter(#accuracy), returnValue: 0.0)
          as double);

  @override
  _i4.Proximity get proximity =>
      (super.noSuchMethod(
            Invocation.getter(#proximity),
            returnValue: _i4.Proximity.unknown,
          )
          as _i4.Proximity);

  @override
  int get major =>
      (super.noSuchMethod(Invocation.getter(#major), returnValue: 0) as int);

  @override
  int get minor =>
      (super.noSuchMethod(Invocation.getter(#minor), returnValue: 0) as int);

  @override
  String get macAddress =>
      (super.noSuchMethod(
            Invocation.getter(#macAddress),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#macAddress),
            ),
          )
          as String);

  @override
  DateTime get timestamp =>
      (super.noSuchMethod(
            Invocation.getter(#timestamp),
            returnValue: _FakeDateTime_0(this, Invocation.getter(#timestamp)),
          )
          as DateTime);

  @override
  _i2.$FlockScanModelCopyWith<_i2.FlockScanModel> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$FlockScanModelCopyWith_1<_i2.FlockScanModel>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i2.$FlockScanModelCopyWith<_i2.FlockScanModel>);
}
