name: flutter_fortunes
description: "Get your Flutter Fortune with a press of a button!"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.5.0
  flutter_riverpod: ^2.6.1
  riverpod_generator: ^2.6.5
  riverpod_annotation: ^2.6.1
  go_router: ^15.1.3
  auto_size_text: ^3.0.0
  audioplayers: ^6.4.0
  flutter_libserialport: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/audio/